/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as PortafolioIndexRouteImport } from './routes/portafolio.index'
import { Route as PortafolioContenidoParaRedesRouteImport } from './routes/portafolio.contenido-para-redes'
import { Route as PortafolioEventosRouteImport } from './routes/portafolio.eventos'
import { Route as PortafolioMarcasRouteImport } from './routes/portafolio.marcas'
import { Route as PortafolioRetratosRouteImport } from './routes/portafolio.retratos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioIndexRoute = PortafolioIndexRouteImport.update({
  id: '/portafolio/',
  path: '/portafolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioContenidoParaRedesRoute =
  PortafolioContenidoParaRedesRouteImport.update({
    id: '/portafolio/contenido-para-redes',
    path: '/portafolio/contenido-para-redes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortafolioEventosRoute = PortafolioEventosRouteImport.update({
  id: '/portafolio/eventos',
  path: '/portafolio/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioMarcasRoute = PortafolioMarcasRouteImport.update({
  id: '/portafolio/marcas',
  path: '/portafolio/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortafolioRetratosRoute = PortafolioRetratosRouteImport.update({
  id: '/portafolio/retratos',
  path: '/portafolio/retratos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/portafolio/contenido-para-redes': typeof PortafolioContenidoParaRedesRoute
  '/portafolio/eventos': typeof PortafolioEventosRoute
  '/portafolio/marcas': typeof PortafolioMarcasRoute
  '/portafolio/retratos': typeof PortafolioRetratosRoute
  '/portafolio/': typeof PortafolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/portafolio/contenido-para-redes': typeof PortafolioContenidoParaRedesRoute
  '/portafolio/eventos': typeof PortafolioEventosRoute
  '/portafolio/marcas': typeof PortafolioMarcasRoute
  '/portafolio/retratos': typeof PortafolioRetratosRoute
  '/portafolio': typeof PortafolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/portafolio/contenido-para-redes': typeof PortafolioContenidoParaRedesRoute
  '/portafolio/eventos': typeof PortafolioEventosRoute
  '/portafolio/marcas': typeof PortafolioMarcasRoute
  '/portafolio/retratos': typeof PortafolioRetratosRoute
  '/portafolio/': typeof PortafolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/portafolio/contenido-para-redes'
    | '/portafolio/eventos'
    | '/portafolio/marcas'
    | '/portafolio/retratos'
    | '/portafolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/portafolio/contenido-para-redes'
    | '/portafolio/eventos'
    | '/portafolio/marcas'
    | '/portafolio/retratos'
    | '/portafolio'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/portafolio/contenido-para-redes'
    | '/portafolio/eventos'
    | '/portafolio/marcas'
    | '/portafolio/retratos'
    | '/portafolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  PortafolioContenidoParaRedesRoute: typeof PortafolioContenidoParaRedesRoute
  PortafolioEventosRoute: typeof PortafolioEventosRoute
  PortafolioMarcasRoute: typeof PortafolioMarcasRoute
  PortafolioRetratosRoute: typeof PortafolioRetratosRoute
  PortafolioIndexRoute: typeof PortafolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio/': {
      id: '/portafolio/'
      path: '/portafolio'
      fullPath: '/portafolio/'
      preLoaderRoute: typeof PortafolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio/contenido-para-redes': {
      id: '/portafolio/contenido-para-redes'
      path: '/portafolio/contenido-para-redes'
      fullPath: '/portafolio/contenido-para-redes'
      preLoaderRoute: typeof PortafolioContenidoParaRedesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio/eventos': {
      id: '/portafolio/eventos'
      path: '/portafolio/eventos'
      fullPath: '/portafolio/eventos'
      preLoaderRoute: typeof PortafolioEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio/marcas': {
      id: '/portafolio/marcas'
      path: '/portafolio/marcas'
      fullPath: '/portafolio/marcas'
      preLoaderRoute: typeof PortafolioMarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portafolio/retratos': {
      id: '/portafolio/retratos'
      path: '/portafolio/retratos'
      fullPath: '/portafolio/retratos'
      preLoaderRoute: typeof PortafolioRetratosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  PortafolioContenidoParaRedesRoute: PortafolioContenidoParaRedesRoute,
  PortafolioEventosRoute: PortafolioEventosRoute,
  PortafolioMarcasRoute: PortafolioMarcasRoute,
  PortafolioRetratosRoute: PortafolioRetratosRoute,
  PortafolioIndexRoute: PortafolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
